$VADIFF Acoustic Diffuse Sound Field
$#        IDDIFF   IDDOM
VADIFF/        1        
$#                                                                         TITLE
NAME VADIFF/ ->1                                                                
$# BLANKTHETAminTHETAmax  STEPth  NBwav1
                       0      1.                        
$# BLANK PHIAmin PHIAmax  STEPph  NBwav2
                       0      1.                        
$# BLANK   IFUNC    SFAC  CONSTr  CONSTi
                       0      1.                        
        END
