$Contact Type 33
$#         IDCTC   NTYPE
CNTAC /        1      33
$#                                                                         TITLE
NAME CNTAC / ->1                                                                
$#    T1SL      T2SL     ISENS     HcontITPRT
        0.        0.         0        0.     
$#PCP    SLFACM     FSVNLIKFOR    PENKIN                                  TLSTIF
             0.        0.    0        0.                                        
$#  FRITYP     VALUE     XDMP1                      IDCNTPTY
CONST              0        0.                              
$#RMVIERODILEAKIAC32               IFRED   DTHKPLK    ADJTOL
    0         0    0                                        
$#   BLANK    SEPSTR    SEPTHK
                              
$#                                      BLANK                              IPRES
                                                                                
        END
        END
