$Contact Type 36
$#         IDCTC   NTYPE
CNTAC /        1      36
$#                                                                         TITLE
NAME CNTAC / ->1                                                                
$#    T1SL      T2SL     ISENS     HcontITPRT
        0.        0.         0        0.     
$#PCP    SLFACM     FSVNL                                                 TLSTIF
             0.        0.                                                       
$#  FRITYP     VALUE     XDMP1
CONST             0.        0.
$#RMVIERODILEAKIAC32          IOMITIFRED   DTHKPLK    ADJTOL
    0         0    0                                        

$#                                      BLANK                              IPRES
                                                                                
        END
