$Contact Type 43
$#         IDCTC   NTYPE
CNTAC /        1      43
$#                                                                         TITLE
NAME CNTAC / ->1                                                                
$#    T1SL      T2SL     ISENS     HcontITPRT
        0.        0.         0        0.     
$#ANK    SLFACM     FSVNL                                        BLANK    TLSTIF
             0.        0.                                                       
$#  FRITYP     VALUE     XDMP1
CONST             0.        0.
$#   BLANK IRMVIAC32          BLANKIFRED
              0                         

$#                                                                    BLANKIPRES
                                                                                
        END
        END
