$SENPTG Sensor Point (Global)
$#         IDSPTIDNODref   RDIST                                   BLANK   RSEAR
SENPTG/        1       0      0.                                                
$#                                                                         TITLE
NAME SENPT / ->1                                                                
$# BLANK    MASS      Ix      Iy      Iz
              0.      0.      0.      0.
        END
