$FASCI Muscular Fascicle Entity  Definition
$#       IDFASCI
FASCI /        1
$#                                                                         TITLE
NAME FASCI / ->1                                                               
$# BLANK    NACT NACTfac
                        
$# BLANK     ALF    PCSA    WMAS QUALIFI   L0fib
                                                
$# BLANK    Tact  Tdeact   Texci    Tref   Ainit   Einit
                                                        
        END
