$PART Type GAP
$#         IDPRT   ATYPE   IDMAT IDVAMAT IDTHMAT  IDPMAT
PART  /        1     GAP       0       0       0       0
$#                                                                         TITLE
NAME PART_1                                                                     
$#  DTELIM    TSCALF   DTRATIO
                              
$#   TCONT    EPSINI  COULFRICIFRED IE2E
                                        
$#   Blank         d
                  0.
$#      
END_PART
