$PART Type SLINK
$#         IDPRT   ATYPE   IDMAT IDVAMAT IDTHMAT  IDPMAT
PART  /        1   SLINK       0       0       0       0
$#                                                                         TITLE
NAME PART_1                                                                     
$#  DTELIM    TSCALF   DTRATIO
                              
$#   TCONT    EPSINI  COULFRICIFRED IE2E
                                        
$#   RDIST                                                       BLANK     INEXT
                                                                                
$#      
END_PART
