$PART Type MUSCLE
$#         IDPRT   ATYPE   IDMAT IDVAMAT IDTHMAT  IDPMAT
PART  /        1  MUSCLE       0       0       0       0
$#                                                                         TITLE
NAME PART_1                                                                     
$#  DTELIM    TSCALF   DTRATIO
                              
$#   TCONT    EPSINI  COULFRICIFRED IE2E
                                        
$# BLANK     ALF    PCSA    WMAS   QUALI   L0fib 
                                CONSTANT        
$#      
END_PART
