$PART Type TSHEL
$#         IDPRT   ATYPE   IDMAT IDVAMAT IDTHMAT  IDPMATIDNUMPAR
PART  /        1   TSHEL       0       0       0       0        
$#                                                                         TITLE
NAME PART_1                                                                     
$#  DTELIM    TSCALF   DTRATIO
                              
$#   TCONT    EPSINI  COULFRIC
                              
$#       H NINT
               
$#      
END_PART
