$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     240              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat240                                                                  
$#  Fmax    Smax
                                                                   
$# BLANK    NLEN NLENfac   ALopt     CSH
                                                               
$# BLANK    NVEL NVELfac   AVmax  CSHORT   CLENG    CMVL
                                                               
$# BLANK    NPAS NPASfac   PEmax     CPE   CDAMP
                                                               
$# BLANK   ITRIG  ELTRIG    NMCY
                                                               
$blank
                                                               
$blank
                                                               
$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
