$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     241              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat241                                                                  
$#  Fmax    Smax   ALopt
                                                                   
$# BLANK   dWdes  nCEdes   dWasc  nCEasc   Arel0   Brel0    Secc    Fecc
                                                                        
$#         BLANK    nPEE    FPEE   lSEE0 dUSEEnl  dUSEEl  dFSEE0
                                                                
$# BLANK   IDAMP  DAMPPE DAMPFSE          NCYCLE
                                                               
$blank
                                                               
$blank
                                                               
$blank
                                                               
$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
