$Material Type 306
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     306              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat306                                                                  
$#     KSI      MASS    IFCOMP
        0.                    
$#   FNmax              DNfail      ETAN
                                        
$#   FTmax              DTfail      ETAT
                                        
$#  ALPHA1    ALPHA2    ALPHA3   DAMrate
                                        
$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
