$Material Type 307
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     307              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat307                                                                  
$#            IELAST     RSURF                                               KSI
FUNC                                                                            
$#   LC1_N     LC2_N     LC3_N     LC4_N     LC5_N     LC6_N     LC7_N     LC8_N
                                                                                
$#ERATE1_N  ERATE2_N  ERATE3_N  ERATE4_N  ERATE5_N  ERATE6_N  ERATE7_N  ERATE8_N
                                                                                
$#   LC1_S     LC2_S     LC3_S     LC4_S     LC5_S     LC6_S     LC7_S     LC8_S
                                                                                
$#ERATE1_S  ERATE2_S  ERATE3_S  ERATE4_S  ERATE5_S  ERATE6_S  ERATE7_S  ERATE8_S
                                                                                
$#   IDELA       ETA
POWER                                   
$#  DamMax     IDRUP                                             IELIM    Ncycle
                                                                                
$---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
