$PLY Type 15
$#         IDPLY    ITYP             RHIFAIL_INP  ISTRAT             KSI
PLY   /        1      15              0.       0                        
$#                                                                         TITLE
NAME PLY   / ->1                                                                
$#    Eft1      Eft2     Gft12     Gft23    NUft12
        0.        0.        0.                    
$#    Efc1      Efc2     Gfc12     Gfc23    NUfc12
        0.        0.        0.        0.        0.
$#      Em       NUm       Kmu        Kp        Ks
        0.        0.        0.        0.        0.
$#      As    IHOMOG     BLANK  NCYCplas
        0.                              
$#   IHARD         a         b         n  SIGMAmax
                  0.        0.        0.        0.
