$RMSSOL Shell-Solid Remeshing
$#      IDRMSSOL  IDTIED   NCYCL                                          DSYSCA
RMSSOL/                                                                         
$#
NAME RMSSOL -> 1
$#          CRIT     KW1     KW2           VCRIT           RMESH
        VARS                                                    
$#         NGEDG   NGTHK XLENGTH
                                
$#
MODELSEL
$#
END_MODELSEL
$#
