$RUPMO Type 8
$#        IDRUPT   IRUPT   IFMON  FILTER IFRCDIR
RUPMO /        1       8                        
$#                                                                         TITLE
NAME RUPMO / ->1                                                                
$#   BLANK   ILAYCRK            IPSTFAIL CONRADscl
                                       0          
$#   BLANK   LCKRlen
                                                
$#   BLANK
                                                
$#   BLANK      INTF
                                                
$#   BLANK
                                                  
