$RUPMO Type 8
$#        IDRUPT   IRUPT   IFMON  FILTER IFRCDIR
RUPMO /        1       9                        
$#                                                                         TITLE
NAME RUPMO / ->1                                                                
$#   BLANK   ILAYCRK  ICONFAIL  IPSTFAIL    RIVRAD
                                       0          
$#   BLANK   LCKRlen
                                                
$#   BLANK  RDLSscal   WLSscal  RDHSscal   WHSscal
                                                  
$#   BLANK      INTF
                                                
$#   BLANK    AFAILN    AFAILS    AFAILT    AFAILB
                                                  
$#   BLANK        AN        AS        AT        AB
                                                  
$#   BLANK        D1        D2
                                                  
